import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {extname} from 'node:path';
import {chromium} from 'playwright';

test('mobile controls and image dialogs pass axe, preserve keyboard focus and keep delayed media stable',async()=>{
 const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),axe=await readFile('node_modules/axe-core/axe.min.js','utf8'),results=[];
 const quality=page=>page.evaluate(async()=>{const result=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});
 try{for(const viewport of [{width:320,height:844},{width:390,height:844},{width:844,height:390}]){
  const context=await browser.newContext({viewport,hasTouch:true}),page=await context.newPage();await page.addInitScript(()=>{window.shifts=[];new PerformanceObserver(list=>{for(const entry of list.getEntries())if(!entry.hadRecentInput)shifts.push(entry.value);}).observe({type:'layout-shift',buffered:true});});
  await context.route('**/*',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/original.svg'){await new Promise(resolve=>setTimeout(resolve,1200));return route.fulfill({contentType:'image/svg+xml',body:await readFile('demo/sample.svg')});}const types={'.js':'text/javascript','.css':'text/css','.webm':'video/webm','.svg':'image/svg+xml','.html':'text/html'},body=await readFile('.'+path);
   if(extname(path)==='.webm'){const range=route.request().headers().range?.match(/^bytes=(\d+)-(\d*)$/),start=Number(range?.[1]||0),end=range?.[2]?Math.min(Number(range[2]),body.length-1):body.length-1;return route.fulfill({status:range?206:200,contentType:'video/webm',headers:{'Accept-Ranges':'bytes',...(range?{'Content-Range':`bytes ${start}-${end}/${body.length}`}:{})},body:body.subarray(start,end+1)});}
   return route.fulfill({contentType:types[extname(path)]||'text/html',body:path.endsWith('/index.html')&&viewport.width===390?body.toString().replaceAll('data-duration="119"','data-duration="3723"'):body});});
  await page.goto('https://component.test/demo/index.html');await page.locator('.media-player').waitFor();await page.addScriptTag({content:axe});assert.deepEqual(await quality(page),[]);
  assert.equal(await page.locator('.plyr__time--duration').textContent(),viewport.width===390?'1:02:03':'01:59');assert.equal(await page.locator('.plyr__time--current').textContent(),'00:00');const controls=await page.locator('.plyr__controls').boundingBox(),progress=await page.locator('.plyr__progress__container').boundingBox(),seek=await page.locator('input[data-plyr=seek]').boundingBox();assert.ok(seek.width>=progress.width*.9,'Seek fills progress container: '+JSON.stringify({viewport,progress,seek}));assert.ok(seek.width>=controls.width*.85,'Seek fills controls: '+JSON.stringify({viewport,controls,seek}));const duration=await page.locator('.plyr__time--duration').boundingBox();assert.ok(duration.width>0&&duration.x+duration.width<=viewport.width);
  const buffer=await page.locator('.plyr__progress__buffer').boundingBox();assert.ok(Math.abs(buffer.x-seek.x)<1&&Math.abs(buffer.width-seek.width)<1,'Seek and buffer tracks align');const current=await page.locator('.plyr__time--current').boundingBox();assert.ok(Math.abs(current.y-duration.y)<1&&duration.x-current.x-current.width<16,'Current and total are adjacent');
  const box=await page.locator('.gallery-stage').boundingBox();await page.locator('.plyr__control--overlaid').click();await page.waitForFunction(()=>document.querySelector('video').currentTime>.1);await page.locator('video').evaluate(v=>v.pause());
  const expected=await page.locator('video').evaluate(v=>{const seconds=Math.floor(v.duration);return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');});assert.equal(await page.locator('.plyr__time--duration').textContent(),expected,'Actual metadata replaces supplied duration');await page.locator('input[data-plyr=seek]').click({position:{x:seek.width*.6,y:seek.height/2}});await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>v.duration*.5&&v.currentTime<v.duration*.7;});assert.ok(Number(await page.locator('input[data-plyr=seek]').inputValue())>=50);
  await page.locator('[data-next]').click();await page.waitForFunction(()=>document.querySelector('img[data-media]').naturalWidth>0);const imageBox=await page.locator('.gallery-stage').boundingBox();assert.ok(Math.abs(box.height-imageBox.height)<1);await page.locator('img[data-media]').evaluate(image=>{image.dataset.original='/original.svg';});
  await page.locator('img[data-media]').click();await page.locator('.image-lightbox[open]').waitFor();assert.equal(await page.locator('.image-lightbox-photo').count(),1);assert.equal(await page.locator('.image-lightbox-photo').evaluate(n=>n.naturalWidth),0);assert.match(await page.locator('.image-lightbox-photo').getAttribute('src'),/original.svg/);await page.waitForFunction(()=>document.querySelector('.image-lightbox-status').hidden);assert.deepEqual(await quality(page),[]);assert.equal(await page.locator('.image-lightbox-toolbar button').count(),3);
  for(const button of await page.locator('.image-lightbox-toolbar button,.image-lightbox-save').all()){const rect=await button.boundingBox();assert.ok(rect.width>=44&&rect.height>=44&&rect.x>=0&&rect.x+rect.width<=viewport.width);assert.equal(await button.locator('svg[aria-hidden=true]').count(),1);}
  await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement.closest('.image-lightbox')));await page.keyboard.press('Escape');await page.locator('.image-lightbox').waitFor({state:'detached'});assert.equal(await page.locator('img[data-media]').evaluate(img=>img===document.activeElement),true);
  const cls=await page.evaluate(()=>shifts.reduce((sum,x)=>sum+x,0));assert.ok(cls<=.01,'Delayed media layout shift '+cls);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);results.push({viewport,cls,violations:0});await context.close();
 }}finally{await browser.close();await mkdir('.artifacts',{recursive:true});await writeFile('.artifacts/quality.json',JSON.stringify(results,null,2));}
});
